#!/bin/bash

update_settings_gradle() {
    local file="$1"

    cat >"${file}" <<'EOF'
pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        google()
        maven { url "https://www.jitpack.io" }
    }
}
includeBuild(new File(["node", "--print", "require.resolve('@react-native/gradle-plugin/package.json')"].execute(null, rootDir).text.trim()).getParentFile().toString())

apply from: new File(["node", "--print", "require.resolve('expo/package.json')"].execute(null, rootDir).text.trim(), "../scripts/autolinking.gradle");
useExpoModules()

rootProject.name = 'reactnative'

dependencyResolutionManagement {
  versionCatalogs {
    reactAndroidLibs {
      from(files(new File(["node", "--print", "require.resolve('react-native/package.json')"].execute(null, rootDir).text.trim(), "../gradle/libs.versions.toml")))
    }
  }
}

include ':app'
EOF

    echo "[OK] settings.gradle atualizado com padrão limpo"
}
